#!/bin/bash
#
# This script installs the latest version of
# zsh, if running on Linux. 
# on MacOS it's just installing oh-my-zsh with the powerlevel10k theme
# and some plugins etc.
# 
#
LBIN=$HOME/.local/bin
GBIN=/usr/local/bin
LFONTS=$HOME/.local/share/fonts
GFONTS=/usr/share/fonts
PATH_TESTFILE=$HOME/test_path
PATH_EXPORT_LOCAL='export PATH="'$LBIN':$PATH"'
PATH_EXPORT_GLOBAL='export PATH="'$GBIN':$PATH"'
USER_ID=$(id -u)
INST=$HOME/inst

is_darwin () {
    case $(uname) in
        Darwin)
            true
            ;;
        *)
            false
            ;;
    esac
}

as_root () {
    case $USER_ID in
        0)
            true
            ;;
        *)
            false
            ;;
    esac
}

check_ubin () {
    if [[ ! -d "$GBIN" ]]; then
        sudo mkdir -p $GBIN
    fi
}

check_lbin () {
    if [[ ! -d "$LBIN" ]]; then
        mkdir -p $LBIN
    fi
}

check_lfonts () {
    if [[ ! -d "$LFONTS" ]]; then
        mkdir -p $LFONTS
    fi
}

check_gfonts () {
    if [[ ! -d "$GFONTS" ]]; then
        mkdir -p $GFONTS
    fi
}

check_path () {
    echo $PATH > $PATH_TESTFILE
    if as_root ; then
        if ! grep -q "${GBIN}" "${PATH_TESTFILE}" ; then
            if ! grep -q "${PATH_EXPORT_GLOBAL}" "$HOME/.zshrc" ; then
                echo "${PATH_EXPORT_GLOBAL}" >> $HOME/.zshrc
            elif ! grep -q "${PATH_EXPORT_GLOBAL}" "$HOME/.bashrc" ; then
                echo "${PATH_EXPORT_GLOBAL}" >> $HOME/.bashrc
            fi
        fi
        export PATH="$GBIN:$PATH"
    else
        if ! grep -q "${LBIN}" "${PATH_TESTFILE}" ; then
            if ! grep -q "${PATH_EXPORT_LOCAL}" "$HOME/.zshrc" ; then
                echo "${PATH_EXPORT_LOCAL}" >> $HOME/.zshrc
            elif ! grep -q "${PATH_EXPORT_LOCAL}" "$HOME/.bashrc" ; then
                echo "${PATH_EXPORT_LOCAL}" >> $HOME/.bashrc
            fi
        fi
        export PATH="$LBIN:$PATH"
    fi
    rm -f $PATH_TESTFILE
}

check_inst () {
    if [[ ! -d "$INST" ]]; then
        mkdir -p $INST
    fi
}

git_installed () {
    which git
    if [[ $? != 0 ]]; then
        echo "git is not installed! Please install git first!"
        exit 1
    fi
}

install_theme () {
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/datflowts/ohmyzsh/master/tools/install.sh)" "" --unattended
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
    git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
}

install_local () {
    check_lbin
    check_path
    #
    # install to ${LBIN}/zsh
    check_inst
    cd $INST
    if ! is_darwin ; then
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/romkatv/zsh-bin/master/install)" "" -d $HOME/.local -e ask
    fi
    install_theme
    cd - >/dev/null
    rm -rf $INST
    install_fonts
    which usermod
    if [[ $? != 0 ]]; then
        which chsh
        if [[ $? != 0 ]]; then
            echo "Note: You'll have to change your default shell manually. Neither usermod nor chsh found."
        else 
            chsh -s ${GBIN}/zsh $USER
        fi
    else
        usermod -s ${GBIN}/zsh $USER
    fi
}

install_global () {
    if is_darwin ; then
        install_theme
        install_fonts
        chsh -s /bin/zsh
        exit 0
    else
        check_ubin
        check_path
        #
        # install to /usr/local/bin
        check_inst
        cd $INST
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/romkatv/zsh-bin/master/install)" "" -d /usr/local -e yes
        install_theme
        cd - >/dev/null
        rm -rf $INST
        for d in $(ls /home); do
            OUSER=$(stat -c "%u" /home/${d})
            OUSER_NAME=$(stat -c "%U" /home/${d})
            cp -rf $HOME/.oh-my-zsh /home/$d/
            cp -rf $HOME/.zshrc /home/$d/
            chown -R $OUSER:$(stat -c "%g" /home/${d}) /home/$d
            which usermod
            if [[ $? != 0 ]]; then
                which chsh
                if [[ $? != 0 ]]; then
                    echo "Note: You'll have to change ${OUSER_NAME}s default shell manually. Neither usermod nor chsh found."
                else 
                    chsh -s ${GBIN}/zsh $OUSER
                fi
            else
                usermod -s ${GBIN}/zsh $OUSER
            fi
        done
        which usermod
        if [[ $? != 0 ]]; then
            which chsh
            if [[ $? != 0 ]]; then
                echo "Note: You'll have to change your default shell manually. Neither usermod nor chsh found."
            else 
                chsh -s ${GBIN}/zsh root
            fi
        else
            usermod -s ${GBIN}/zsh root
        fi
        cp -rf $HOME/.oh-my-zsh /etc/skel/
        cp -rf $HOME/.zshrc /etc/skel/
        install_fonts
#        sed -i 's/\/bin\/bash/\/usr\/local\/bin\/zsh/g' /etc/passwd
        if [[ -f "/etc/adduser.conf" ]]; then
            sed -i 's/\/bin\/bash/\/usr\/local\/bin\/zsh/g' /etc/adduser.conf
        elif [[ -f "/etc/default/useradd" ]]; then
            sed -i 's/\/bin\/bash/\/usr\/local\/bin\/zsh/g' /etc/default/useradd
        fi
    fi
}

install_fonts () {
    if is_darwin ; then
        brew tap hombrew/cask-fonts
        brew install --cask font-jetbrains-mono-nerd-font
        echo "Jetbrains Mono Nerd Font installed. Get the best experience by enabling it in your terminal."
        echo "If using iTerm2, p10k configure will ask to install Meslo Nerd Font (recommended)."
    else
        case as_root in
            true)
                check_gfonts
                cd $GFONTS
                curl -fLo "Meslo LG M DZ Regular Nerd Font Complete.ttf" https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Meslo/M-DZ/Regular/complete/Meslo%20LG%20M%20DZ%20Regular%20Nerd%20Font%20Complete.ttf
                curl -fLo "Meslo LG M DZ Regular Nerd Font Complete Mono.ttf" https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Meslo/M-DZ/Regular/complete/Meslo%20LG%20M%20DZ%20Regular%20Nerd%20Font%20Complete%20Mono.ttf
                ;;
            *)
                check_lfonts
                cd $LFONTS
                curl -fLo "Meslo LG M DZ Regular Nerd Font Complete.ttf" https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Meslo/M-DZ/Regular/complete/Meslo%20LG%20M%20DZ%20Regular%20Nerd%20Font%20Complete.ttf
                curl -fLo "Meslo LG M DZ Regular Nerd Font Complete Mono.ttf" https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Meslo/M-DZ/Regular/complete/Meslo%20LG%20M%20DZ%20Regular%20Nerd%20Font%20Complete%20Mono.ttf
                ;;
        esac
        echo "Meslo Nerd Font installed. Get the best experience by enabling it in your terminal."
    fi

    echo "Note: you'll have to restart your terminal before you can use the new font."
    cd
}

git_installed
if ! is_darwin ; then
    if as_root ; then
        echo "Installing ZSH globally."
        install_global
        exit 0
    else
        echo "Installing ZSH locally for $USER."
        echo "Run with 'sudo' or directly as root for a global install."
        install_local
        exit 0
    fi
else
    echo "Installing ZSH Theme."
    install_theme
    install_fonts
    chsh -s /bin/zsh
    exit 0
fi