#!/bin/bash

HOST="manjaro.datmac.com"
BRIDGEHOST="fedora.datmac.com"
CMD="manjaro"
DEFUSER="datflow"
VNCPORT=5969
TUNPORT=5901
BRIDGEPORT=9998

if [[ "$1" = "help" ]] || [[ "$1" = "h" ]]; then
	if [[ "$2" = "X11" ]]; then
		echo "Usage: '$CMD X11 [-username] <command>'"
	elif [[ "$2" = "ssh" ]]; then
		echo "Usage: '$CMD [-username] [command]'"
	elif [[ "$2" = "vnc" ]]; then
		echo "Usage: '$CMD vnc'"
	else
		echo "---- #### ---- '$CMD' HELP ---- #### ----"
		echo " - Use 'vnc' as single argument to use VNC-Connection"
		echo " - 'X11' as first argument will need second arg"
		echo "	 to provide user and a third one for the command"
		echo "	 to use X11-Forwarding for. see '$CMD h X11'"
		echo " - If you pass a username as first arg, you'll SSH as"
		echo "	 that user to $HOST. See '$CMD h user'"
		echo " - whithout any argument, you'll SSH as $DEFUSER"
		echo " - However you can provide another argument after username"
		echo "	 if you want to execute a command directly"
		echo " - When you provide any different argument, you'll"
		echo "	 execute the given argument as a command directly"
		echo "	 as $DEFUSER"
		echo " ---- #### ----- 	    EXAMPLES      ----- #### ----"
		echo " - '$CMD vnc' => VNC to $HOST via SSH Tunnel"
		echo "    between Ports $TUNPORT and $VNCPORTi via"
		echo "    $BRIDGEHOST on $BRIDGEPORT"
		echo " - '$CMD X11 -foo firefox' => X11-Forward Firefox"
		echo " - '$CMD -bar' => SSH to $HOST as bar'"
		echo " - '$CMD foobar => runs 'foobar' as $DEFUSER"
		echo " - '$CMD' => SSH to $HOST as $DEFUSER"
		echo "--------------------------------------------------------"
	fi
elif [[ "$1" = "vnc" ]]; then
	ssh -L ${BRIDGEPORT}:${HOST}:22 -N -f ${DEFUSER}@${BRIDGEHOST}
	ssh -L ${TUNPORT}:localhost:${VNCPORT} -N -f -p ${BRIDGEPORT} ${DEFUSER}@localhost
	vncviewer localhost:${TUNPORT} &
elif [[ "$1" = "X11" ]]; then
	if [[ "$2" =~ ^[-][[:lower:]_]([[:lower:]0-9_-]{0,31}|[[:lower:]0-9_-]{0,30}\$)$ ]];then
		ssh -X ${2:1}@${HOST} "$3"
	else
		ssh -X ${DEFUSER}@${HOST} "$2"
	fi
elif [[ "$1" =~ ^[-][[:lower:]_]([[:lower:]0-9_-]{0,31}|[[:lower:]0-9_-]{0,30}\$)$ ]];then
	ssh ${1:1}@${HOST} "$2"
else
	ssh ${DEFUSER}@${HOST} "$1"
fi
